-- ================================================================================
-- Test suite.
-- ================================================================================

-- The module.
local Test = { }


-- ================================================================================
-- Privates

-- ----------------------------------------
-- Private constants

local test_modules = {
   { "Base64",     require("kintastic/tests/Base64") },
   { "ColorUtils", require("kintastic/tests/ColorUtils") },
   { "Crc32",      require("kintastic/tests/Crc32") },
   { "Encode",     require("kintastic/tests/Encode") },
}

local test_modules_by_name = { }
for i, _ in ipairs(test_modules) do
   local name, test_module = table.unpack(_)
   test_modules_by_name[name] = test_module
end


-- ----------------------------------------
-- Private function info_msg
-- Private function error_msg

local function info_msg(msg)  printToAll(msg, Color.White) end
local function error_msg(msg) printToAll(msg, Color.Red)   end


-- ----------------------------------------
-- Private function run_test

local function run_test(state, name, f, ...)
   local success, rv = pcall(f, state, ...)
   if not success then
      error_msg(name .. ": failed (Exception)")
      error_msg(rv)
   elseif not rv then
      printToAll(name .. ": failed", Color.Red)
   else
      info_msg(name .. ": ok")
   end
end


-- ----------------------------------------
-- Private function run_test_module

local function run_test_module(name, test_module)
   if not test_module then
      error_msg("No test module named \"" .. name "\"")
      return
   end

   info_msg("[[" .. name .. "]]")
   local state = { }
   for i, test in ipairs(test_module) do
      run_test(state, table.unpack(test))
   end
end


-- ================================================================================
-- Public interface

-- ----------------------------------------
-- Public function Test.run_tests

function Test.run_tests(selected_tests)
   if selected_tests then
      for i, name in ipairs(selected_tests) do
         run_test_module(name, test_modules_by_name[name])
      end
   else
      for i, _ in ipairs(test_modules) do
         run_test_module(table.unpack(_))
      end
   end
end


-- ================================================================================

return Test
